### ISSUE TITLE
Error: /forum/admin/plugins/sanitizehtml Not Found

### ISSUE THREAD

**Issue by Teresa-Hale-DHQ** [akhoury/nodebb-plugin-sanitizehtml#19]
Running NodeBB 1.17.x
OS: Ubuntu 18.04
Log output:
```
2021-05-12T17:59:21.545Z [4567/16421] - warn: [plugins] Unable to load library for: nodebb-plugin-sanitizehtml
2021-05-12T17:59:21.547Z [4567/16421] - error: Error: Cannot find module './meta'
Require stack:
- /home/forum/src/plugins/index.js
- /home/forum/src/meta/configs.js
- /home/forum/src/meta/index.js
- /home/forum/src/start.js
- /home/forum/require-main.js
- /home/forum/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Object.<anonymous> (/home/forum/node_modules/nodebb-plugin-sanitizehtml/index.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by akhoury** [comment]
https://github.com/akhoury/nodebb-plugin-sanitizehtml/commit/5219102e729789b5d82697dd4351f6d24ede2372 

use 1.0.0 for 1.17.x+
