### ISSUE TITLE
v0.8.x compatibility

### ISSUE THREAD

**Issue by Fidelix** [akhoury/nodebb-plugin-sanitizehtml#5]
Apparently this plugin is not working with this version of NodeBB.

```
7/9 15:52 [40085] - error: /somepath/nodebb/node_modules/nodebb-plugin-sanitizehtml/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/somepath/nodebb/node_modules/nodebb-plugin-sanitizehtml/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
7/9 15:52 [40085] - warn: [plugins] Unable to parse library for: nodebb-plugin-sanitizehtml
```

Any tips on how to solve this? If you don't have the time, I can try to fix it and create a PR if it's simple enough (I'm not very knowledgeable with NodeJS).

**Comment by akhoury** [comment]
I'll investigate
